### ISSUE TITLE
Русифицировать и подписать поля в некоторых контроллерах

### ISSUE THREAD

**Issue by AlukardBF** [AlukardBF/construct_web#16]
В частности в поиске пользователей у админа и почти весь Group контроллер. Убрать шуточные надписи, восклицательные знаки и т.д. Может быть что-то еще.

**Comment by boolenTFV** [comment]
Дим, это супер не приоритетная задача, нам бы функционал допилить

**Comment by AlukardBF** [comment]
cef21a32b7c2b33e61b3f0675cf3995661389a2c
