### ISSUE TITLE
Удаление подсекций

### ISSUE THREAD

**Issue by boolenTFV** [AlukardBF/construct_web#2]
**Добавить удаление подсекций на странице редактирования курса**
Сделать в контроллере subsection action - 'delete'. И добавить кнопку удаления для каждого subsection в course/edit.

**Comment by AlukardBF** [comment]
Сделаю

**Comment by AlukardBF** [comment]
https://github.com/AlukardBF/construct_web/commit/f2ee7825bf2ffeac8b3b960a78dd6cbe9c22c53b
