### ISSUE TITLE
Вывод настроек курса

### ISSUE THREAD

**Issue by romaborzin** [AlukardBF/construct_web#5]
Сделать верхнее меню таб для секций
"Главы" "Приложения" "Графический материал"
Далее каждая подсекция будет в виде аккордеона, для облегченного поиска. После нажатия на который появятся текстовые поля для редактирования а так же кнопка удаления подраздела

**Comment by AlukardBF** [comment]
Там же в настройках курса при сохранении какого либо из полей (например, описание уже созданной главы), все остальные текстовые поля заполняться тем же значением. Скорее всего проблема в одинаковых #id

**Comment by AlukardBF** [comment]
Сделано в https://github.com/AlukardBF/construct_web/commit/32d78261a96682590f83f813b82ecb52d094b73c
Теперь каждая секция это свой Tab, а главы в секциях раскиданы по аккардионам. Попутно жестко зарефакторил show.phtml, для использования кода повторно, выделил формирование глав в subsection_partial.phtml. И еще изменения по мелочи
